clc;
clear all;
figure;
plot(out.vL);
hold on;
plot(out.iL);
grid minor;
legend('Inductor Voltage','Inductor Current');
xlabel('Voltage(V)/Current(A)');
ylabel('Time(s)');
title('Inductor Current and Voltage');
figure;
plot(out.vo);
grid minor;
xlabel('Voltage(V)');
ylabel('Time(s)');
title('Output Voltage');
figure;
plot(out.vd);
hold on;
plot(out.id);
grid minor;
legend('Diode Voltage','Diode Current');
xlabel('Voltage(V)/Current(A)');
ylabel('Time(s)');
title('Diode Current and Voltage');
figure;
plot(out.vs);
hold on;
plot(out.is);
grid minor;
legend('Switch Voltage','Switch Current');
xlabel('Voltage(V)/Current(A)');
ylabel('Time(s)');
title('Switch Current and Voltage');