figure;
plot(out.vL);
hold on;
plot(out.iL);
grid minor;
legend('Inductor Voltage','Inductor Current');
ylabel('Voltage(V)/Current(A)');
xlabel('Time(s)');
title('Inductor Current and Voltage');
figure;
plot(out.vo);
grid minor;
ylabel('Voltage(V)');
xlabel('Time(s)');
title('Output Voltage');
figure;
plot(out.vd);
hold on;
plot(out.id);
grid minor;
legend('Diode Voltage','Diode Current');
ylabel('Voltage(V)/Current(A)');
xlabel('Time(s)');
title('Diode Current and Voltage');
figure;
plot(out.vs);
hold on;
plot(out.is);
grid minor;
legend('Switch Voltage','Switch Current');
ylabel('Voltage(V)/Current(A)');
xlabel('Time(s)');
title('Switch Current and Voltage');